import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

/**
 * demo:files — safe demonstration corpus generator.
 * Creates a realistic messy folder (Documents, Images, Videos, ...) with
 * sample files. Nothing is deleted; the target is created if missing;
 * it refuses to write outside the chosen directory.
 */

const README_TEXT = `FileMind demo corpus
====================
This folder was generated by "npm run demo:files" so you can try the app safely.
All files are tiny synthetic samples. Nothing here is important.`;

interface DemoFile {
  name: string;
  body: string | Buffer;
}

function repeat(text: string, n: number): string {
  return Array(n).fill(text).join('\n');
}

function buildCorpus(): DemoFile[] {
  const files: DemoFile[] = [];
  const push = (name: string, body: string | Buffer) => files.push({ name, body });

  // documents
  push('invoice_2026_03_acme.pdf', repeat('%PDF-1.4 INVOICE Acme Corp total due $1,240', 40));
  push('invoice_2026_04_globex.pdf', repeat('%PDF-1.4 INVOICE Globex Ltd total due $980', 40));
  push('lease_agreement_signed.pdf', repeat('%PDF-1.4 LEASE AGREEMENT tenant landlord signature', 60));
  push('meeting_notes_2026-05-12.txt', repeat('Meeting notes: quarterly roadmap, budget review, hiring plan.', 30));
  push('recipes_to_try.md', repeat('# Recipes\n- lemon pasta\n- shakshuka\n- banana bread', 10));
  push('resume_john_doe.docx', repeat('PK DOCX John Doe resume experience skills education', 50));
  push('warranty_scanner_page.jpg', Buffer.from([0xff, 0xd8, 0xff, 0xe0, ...crypto.randomBytes(900)]));

  // spreadsheets & presentations
  push('budget_2026.xlsx', repeat('PK XLSX budget revenue expenses Q1 Q2 Q3 Q4', 40));
  push('expenses_export.csv', 'date,item,amount\n2026-01-05,office chair,189\n2026-02-11,monitor,320\n');
  push('client_pitch_deck.pptx', repeat('PK PPTX pitch slide market opportunity pricing', 45));

  // images
  push('IMG_20260415_113022.jpg', Buffer.from([0xff, 0xd8, 0xff, 0xe0, ...crypto.randomBytes(1200)]));
  push('screenshot 2026-06-01 at 10.22.31.png', Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47]), crypto.randomBytes(800)]));
  push('family_photo_beach.jpg', Buffer.from([0xff, 0xd8, 0xff, 0xe0, ...crypto.randomBytes(1500)]));
  push('logo_draft_v2.psd', repeat('8BPS photoshop layer mask draft', 30));

  // videos / audio
  push('VID_20260501_birthday.mp4', Buffer.concat([Buffer.from([0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70]), crypto.randomBytes(2000)]));
  push('vacation_timelapse.mov', Buffer.concat([Buffer.from([0x00, 0x00, 0x00, 0x14, 0x66, 0x74, 0x79, 0x70]), crypto.randomBytes(2200)]));
  push('podcast_episode_12.mp3', Buffer.concat([Buffer.from([0x49, 0x44, 0x33, 0x03]), crypto.randomBytes(1000)]));
  push('voice_memo_ideas.m4a', crypto.randomBytes(900));

  // archives
  push('photos_backup_2025.zip', Buffer.concat([Buffer.from([0x50, 0x4b, 0x03, 0x04]), crypto.randomBytes(1300)]));
  push('old_project_archive.tar.gz', Buffer.concat([Buffer.from([0x1f, 0x8b]), crypto.randomBytes(700)]));

  // code & data
  push('utils.js', repeat('function formatDate(d){ return d.toISOString(); }', 20));
  push('analyze_sales.py', repeat('import pandas as pd\ndf = pd.read_csv("expenses_export.csv")', 15));
  push('config.json', JSON.stringify({ theme: 'dark', autosave: true }, null, 2));
  push('site_backup_2026.zip', Buffer.concat([Buffer.from([0x50, 0x4b, 0x03, 0x04]), crypto.randomBytes(1100)]));

  // messy strays (no extension, weird names)
  push('README', Buffer.from(README_TEXT));
  push('download (1)', Buffer.from('unknown stray file'));
  push('untitled', Buffer.from('unknown stray file 2'));

  return files;
}

export function generateDemoFiles(targetDir: string): { created: number; dir: string } {
  if (!path.isAbsolute(targetDir)) {
    throw new Error('Please choose a folder — FileMind only writes inside the folder you pick.');
  }
  fs.mkdirSync(targetDir, { recursive: true });

  // A couple of nested messes, like real life.
  const subdirs = ['Downloads misc', 'old stuff', 'Camera Imports'];
  for (const d of subdirs) fs.mkdirSync(path.join(targetDir, d), { recursive: true });

  let created = 0;
  for (const f of buildCorpus()) {
    const dir = f.name.includes('IMG_') || f.name.includes('screenshot')
      ? path.join(targetDir, 'Camera Imports')
      : f.name.includes('archive') || f.name.includes('backup')
        ? path.join(targetDir, 'old stuff')
        : targetDir;
    const p = path.join(dir, f.name);
    fs.writeFileSync(p, f.body);
    created += 1;
  }
  return { created, dir: targetDir };
}

// CLI entry: npm run demo:files [-- targetDir]
if (require.main === module) {
  const arg = process.argv[2] ?? path.join(process.cwd(), 'FileMindDemo');
  try {
    const out = generateDemoFiles(path.resolve(arg));
    console.log(`Created ${out.created} demo files in: ${out.dir}`);
    console.log('Open FileMind → Organize, add that folder, and take the pipeline for a spin.');
  } catch (err) {
    console.error('Could not create demo files:', (err as Error).message);
    process.exit(1);
  }
}
