// AUTO-GENERATED by scripts/set-variant.mjs — do not edit by hand.
// Diagnostic variant: normal
export const VARIANT_NAME = "normal" as string;
export const DISABLE_ONNX = false;
export const DISABLE_WATCHER = false;
