#!/usr/bin/env node
/**
 * Writes src/main/variant.ts for diagnostic builds.
 *
 * Variants (crash-isolation experiment):
 *   normal — faithful app: ONNX enabled, watcher enabled
 *   A      — ONNX DISABLED (no require, no session), watcher enabled
 *   B      — ONNX enabled, filesystem watcher DISABLED
 *   C      — both disabled
 *
 * These flags PREVENT the actual initialization code from executing
 * (verified by regression tests) — they do not merely hide UI features.
 */
import fs from 'node:fs';
import path from 'node:path';

const variant = process.argv[2] ?? 'normal';
const presets = {
  normal: { disableOnnx: false, disableWatcher: false },
  A: { disableOnnx: true, disableWatcher: false },
  B: { disableOnnx: false, disableWatcher: true },
  C: { disableOnnx: true, disableWatcher: true },
};
const flags = presets[variant];
if (!flags) {
  console.error(`Unknown variant "${variant}". Use one of: ${Object.keys(presets).join(', ')}`);
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/set-variant.mjs — do not edit by hand.
// Diagnostic variant: ${variant}
export const VARIANT_NAME = ${JSON.stringify(variant)} as string;
export const DISABLE_ONNX = ${flags.disableOnnx};
export const DISABLE_WATCHER = ${flags.disableWatcher};
`;
fs.writeFileSync(path.join(process.cwd(), 'src', 'main', 'variant.ts'), out);
console.log(`variant.ts written for "${variant}":`, flags);
